version: 1
disable_existing_loggers: true
formatters:
  simple:
    format: '%(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  app:
    level: DEBUG
    handlers: [console]
    propagate: no